apiVersion: batch/v1
kind: CronJob
metadata:
  name: restart-deployments
  namespace: cronjob
spec:
  concurrencyPolicy: Forbid 
  schedule: '0 0 */3 * *'    
  jobTemplate:
    spec:
      backoffLimit: 2 
      activeDeadlineSeconds: 600 
      template:
        spec:
          serviceAccountName: restart-deployments 
          restartPolicy: Never
          containers:
            - name: kubectl1
              image: bitnami/kubectl
              command: 
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment/nginx-deployment'
            - name: kubectl2
              image: bitnami/kubectl 
              command: 
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment/mongo-deployment'
