apiVersion: batch/v1
kind: CronJob
metadata:
  name: restart-deployments
spec:
  schedule: "0 0 * * *"  # This cron schedule means midnight UTC every day
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: restart-container
            image: bitnami/kubectl:latest  # You can use any image with kubectl
            command:
            - /bin/sh
            - -c
            - |
              kubectl rollout restart deployment dummy-deployment
          restartPolicy: OnFailure
