apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restart-deployments
  namespace: cronjob
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: restart-deployments
subjects:
  - kind: ServiceAccount
    name: restart-deployments
    namespace: cronjob
