apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restart-deployments
  namespace: cronjob
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    resourceNames: ["nginx-deployment", "mongo-deployment"]
    verbs: ["get", "patch"]
